Attempt to update the disturbance immediately in the python/RK4 file
lf-lang/experimental-lingua-franca pull request #4
Opened 2022-06-15 23:55 UTC by YiweiIvy

Thanks for enabling method declaration in python! I tried to create the methods for updating the disturbance immediately in the python/RK4 file. 

I created a state called "elapsed_time" which serves as a time stamp that records the time when the state was outputted last time. And the time interval between "the logical time at which current update happens" and last "elapsed_time" stamp is the time interval used for ODE. 

I also combined the "d" and "t" reaction. Now the update will be triggered when either a disturbance is introduced or a sample period of time has elapsed. It will only be triggered once even if both happen at the same time.

The code complies and graph generation works fine, but the graph looks the same as before because the change is so small that it does not show in the graph.

2022-06-17 01:39 UTC, edwardalee requested changes
This is looking good, but see my questions.

2022-06-17 21:15 UTC, YiweiIvy commented on Python/src/FurutaPendulum/PendulumSimulationRK4.lf
> +        time_interval = (lf.time.logical_elapsed() - self.elapsed_time) * 1e-9
That makes sense! I will move line 168 below line 139, so that it will update self.elapsed_time right after we've gotten the time interval for the last cycle instead of after calling output_state().

2022-06-17 21:48 UTC, YiweiIvy commented on Python/src/FurutaPendulum/PendulumSimulationRK4.lf
> +        def f(x):
It seems like my RK4_ODE() function cannot have access to f(x) if it is not defined in the same method (like when functions are not defined in the same frame or in their parent frames in python)

2022-06-17 22:00 UTC, edwardalee commented on Python/src/FurutaPendulum/PendulumSimulationRK4.lf
> +        def f(x):
Even if f() is defined as a method?  I think there is a test case where one method calls another.

2022-06-17 22:02 UTC, YiweiIvy commented on Python/src/FurutaPendulum/PendulumSimulationRK4.lf
> +        def f(x):
Oh right that should work!

2022-06-17 22:02 UTC, edwardalee commented on Python/src/FurutaPendulum/PendulumSimulationRK4.lf
> +        time_interval = (lf.time.logical_elapsed() - self.elapsed_time) * 1e-9
It would be a good idea to develop a test case where it becomes very obvious if the updates are not right, like something with first order dynamics and large step sizes.

2022-06-17 22:26 UTC, YiweiIvy commented on Python/src/FurutaPendulum/PendulumSimulationRK4.lf
> +        def f(x):
I tried but it still doesn't work somehow. On the website, there is only an example with reactions calling methods but not methods calling methods. And I tested with a modified test case on the website, it does not work either.

target Python
main reactor Methods {
    state foo(2)
    method getFoo() {=
        return self.foo
    =}
    method add(x) {=
        x = getFoo()
        self.foo += x  
    =}
    reaction(startup){=
        print(f"Foo is initialized to {self.getFoo()}.")
        self.add(40)
        print(f"2 + 40 = {self.getFoo()}.")
    =}
}

It will error when calling self.add(40) with message: NameError: name 'getFoo' is not defined.

2022-06-17 22:38 UTC, YiweiIvy commented on Python/src/FurutaPendulum/PendulumSimulationRK4.lf
> +        def f(x):
Sorry, it works:)

2022-06-30 21:45 UTC, YiweiIvy commented on Python/src/FurutaPendulum/PendulumSimulationRK4.lf
> +        time_interval = (lf.time.logical_elapsed() - self.elapsed_time) * 1e-9
I did a test by amplifying the graph within a small time interval. It looks like the disturbance is updating fine. The sample time period is 10 msec (update at 10 msec and 20 msec), and the disturbance is introduced at 12 msec (the small bend at 12 msec). And the updates regarding other problems are fixed in the new commit.
![Screen Shot 2022-06-30 at 14 40 53](https://user-images.githubusercontent.com/105534550/176784096-24c60af6-98f2-4c64-97d7-bcced68cf97f.png)
)

2022-07-03 16:36 UTC, edwardalee requested changes

2022-07-03 16:36 UTC, edwardalee commented on Python/src/FurutaPendulum/PendulumSimulationEuler.lf
> +    reaction(d) {=
Moving the reaction to d ahead of the state update does not look right to me. If the disturbance is simultaneous with the sample period, then it will effectively act as if the disturbance had occurred _ahead_ of time by one sample period because it updates the angular velocity, then updates the state as if one sample period had elapsed since the velocity was updated.

I think we need a test case where the dynamics are much simpler so that it becomes totally obvious what the effect of the disturbance should be.  E.g., a single state variable _x_ with, say, dx/dt = 1. Set sample period to 1 sec, and forward Euler should be perfectly accurate, yielding time-value pairs (0,0), (1,1), (2,2), ...

Then introduce a disturbance at 1500 msec that changes dx/dt = 2.  Now, the time value pairs generated should be (0,0), (1,1), (1.5,1.5), (2.0,2.5), (3.0,4.5), ...

2022-07-03 16:36 UTC, edwardalee commented on Python/src/FurutaPendulum/PendulumSimulationRK4.lf
> +    method calculate_derivatives(x){=
What is the argument x here? It seems to not be used in the body of the method.

2022-07-03 16:36 UTC, edwardalee commented on Python/src/FurutaPendulum/PendulumSimulationRK4.lf
> +                self.x[1] += d.value
Again, I think that handling the disturbance before updating the state is not correct.  This is why we need the simpler test case.  We need a test case where we know _exactly_ what the output should be, which is not the case with the Furuta pendulum.

2022-07-21 17:29 UTC, YiweiIvy commented
I've made the modifications to the RK4 file based on what we discussed last Tuesday. And SmallTest.lf graph is now a stem plot with points labelled with their cooridinates
![Screen Shot 2022-07-21 at 10 29 37](https://user-images.githubusercontent.com/105534550/180276556-4f2d186c-21af-4b66-bbb4-57e88e3ded9f.png)
.

2022-07-21 22:54 UTC, edwardalee commented
Yes, this looks right!

2022-07-27 18:33 UTC, merged